### ISSUE TITLE
The image is not displayed

### ISSUE THREAD

**Issue by IkumiMashiba** [gilbitron/Raneto#311]
Am i wrong?

step.1
git clone https://github.com/appsecco/raneto-docker.git

step.2
cd raneto-docker
mkdir images
copy /mydir/atom-1.png .

step.3
docker-compose.yml
```
version: '2'
services:
  raneto:
    container_name: raneto
    image: appsecco/raneto
    volumes:
      - ./raneto-docker/images/:/data/images/
      - ./raneto-docker/content/:/data/content/
      - ./raneto-docker/config/config.default.js:/opt/raneto/example/config.default.js
    ports:
      - "3000:3000"
```

step.4
make md file

./raneto-docker/content/Ikumi/atom.md
```
Atom
![Atom png](%image_url%/atom-1.png)
```

step.5
docker-compose up -d

step.6
browse
```
http://localhost:3000/Ikumi/atom
```

![image](https://user-images.githubusercontent.com/12806774/71239382-c604a780-2349-11ea-8f36-cbc67f6567a2.png)
